# Generated by Django 2.1.4 on 2018-12-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('status', models.CharField(choices=[('TD', 'Nieuw'), ('IP', 'Mee Bezig'), ('NV', 'Afgerond'), ('AP', 'Goedgekeurd')], default='TD', max_length=2)),
            ],
        ),
    ]
