# Generated by Django 2.1.4 on 2018-12-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_answering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
